## 事务失效

https://blog.csdn.net/shichen2010/article/details/121792816

从动态代理到事务注解失效

Spring 5.x 中 AOP 默认依旧使用 JDK 动态代理，如果需要默认使用CGLIB动态代理可以通过配置项<aop:aspectj-autoproxy proxy-target-class="true"/>来进行配置。

SpringBoot 2.x 开始，为了解决使用 JDK 动态代理可能导致的类型转化异常而默认使用 CGLIB。如果需要默认使用 JDK 动态代理可以通过配置项spring.aop.proxy-target-class=false来进行修改，proxyTargetClass配置已无效。





在同一个类的非事务方法中调用了另一个事务方法



```java
public class UserService extends BaseServerTest {

    private static final Logger logger = Logger.getLogger(PropagationTest.class);

    @Autowired
    UserMapper userMapper;

    @Test
    public void a() {
        try {
            b();
        } catch (Exception e) {
            throw new RuntimeException();
        }
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW, readOnly = false, rollbackFor = RuntimeException.class)
    public void b() {
        try {
            userMapper.saveNews(new JSONArray());
        } catch (Exception e) {
            throw new RuntimeException();
        }
    }
}

```

## 事务传播





## 事务冲突

https://www.jianshu.com/p/74ee5c0276ed

若当前存在事务，则加入该事务，若不存在事务，则新建一个事务。

```java
class Test1(){ 
  @Transactional(propagation = Propagation.REQUIRED)
  function A(){
    T2.B();
  }
}
class T2(){
  @Transactional(propagation = Propagation.REQUIRED)
  function B(){
    System.out.println("T2 的 B 方法被调用");
  }
}
```

1）、若B方法抛出异常，A方法进行捕获，A会抛出异常，因为T2标志回滚，T1标志提交，产生冲突。（若希望A不抛出异常则需要在A的catch中添加，类似如下代码）

```java
function A(){
  ...
  try{
    ...
    ...
    T2.B();
  }catch(Exception e){
    TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();
    e.printStackTrace();
  }
}
```



## 多线程事务

https://blog.csdn.net/m0_72134256/article/details/125352003